packages:
  git:
    darwin:
      via: brew 
      name: git # can be used to overwrite the default pkg name used when installing via pkg managers
    linux-debian:
      via: apt
      name: git
    groups: [ "base", "node_development" ]
  neovim:
    darwin:
      via: brew
    linux-debian:
      via: apt
    groups: [ "base", "node_development" ]
  jq:
    darwin:
      via: brew
    linux-debian:
      via: apt
    groups: [ "base", "node_development" ]
  zsh:
    darwin:
      via: brew
    linux-debian:
      via: apt
    groups: [ "base", "node_development" ]
  starship:
    darwin:
      via: brew
    linux-debian:
      via: script # an external "run_onchange" script handles this installation
    groups: [ "base", "node_development" ]
  mise:
    darwin:
      via: script
    linux-debian:
      via: script
    groups: [ "node_development" ]
