packages:
  git:
    darwin:
      via: brew
      name: git
    linux-debian:
      via: apt
      name: git
    groups: [ "base", "node_development" ]
  neovim:
    darwin:
      via: brew
      name: neovim
    linux-debian:
      via: apt
      name: neovim
    groups: [ "base", "node_development" ]
  jq:
    darwin:
      via: brew
      name: jq
    linux-debian:
      via: apt
      name: jq
    groups: [ "base", "node_development" ]
  zsh:
    darwin:
      via: brew
      name: zsh
    linux-debian:
      via: apt
      name: zsh
    groups: [ "base", "node_development" ]
  starship:
    darwin:
      via: brew
      name: starship
    linux-debian:
      via: script
    groups: [ "base", "node_development" ]
  mise:
    darwin:
      via: script
    linux-debian:
      via: script
    groups: [ "node_development" ]
